In [321]:
import pandas as pd

orders = pd.read_csv("data/orders.csv")
customers = pd.read_csv("data/customers.csv")
products = pd.read_csv("data/products.csv")

In [322]:
orders.head()

,order_id,order_date_raw,customer_id,product_id,region_raw,sales_channel_raw,payment_method_raw,quantity_raw,unit_price_raw,discount_pct_raw,status_raw,shipping_days_raw,customer_rating_raw
0,ORD007682,2025-07-20,CUST00512,P0013,Agadir,Mobile App,Bank Transfer,1.0,3322.7,20.0,DELIVERED,4.0,4.9
1,ORD023476,2025-11-18,CUST00004,P0042,Marrakech,Marketplace,Card,5.0,409.62,20.0,CANCELLED,2.0,NaN
2,ORD011425,2025-11-13,CUST01117,P0090,Agadir,Website,Card,4.0,2262.94,0.0,DELIVERED,6.0,4.6
3,ORD026708,2025-04-24,CUST01059,P0046,Fes,Website,Cash,1.0,1916.7,0.0,CANCELLED,4.0,NaN
4,ORD010833,05-01-2025,CUST00978,P0067,Fes,Marketplace,Card,1.0,2125.78,15.0,PENDING,4.0,NaN

In [323]:
customers.head()

,customer_id,signup_date,customer_segment_raw,loyalty_tier,age_group,home_region_raw
0,CUST00001,2025-11-24,VIP,SILVER,25-34,Agadir
1,CUST00002,2025-09-02,REGULAR,SILVER,35-44,TANGER
2,CUST00003,2024-09-19,REGULAR,SILVER,45-54,Marrakech
3,CUST00004,2024-11-08,REGULAR,SILVER,25-34,Kenitra
4,CUST00005,2023-09-02,REGULAR,BRONZE,35-44,Casablanca

In [324]:
products.head()

,product_id,product_name,category,subcategory,brand,cost_price,list_price
0,P0001,Nexa_Phones_1,Electronics,Phones,UrbanX,84.02,124.67
1,P0002,Atlas_Phones_2,Electronics,Phones,Aura,1230.99,2472.26
2,P0003,Nova_Phones_3,Electronics,Phones,Nexa,92.44,132.73
3,P0004,Nova_Wearables_4,Electronics,Wearables,UrbanX,427.98,749.34
4,P0005,Pulse_Wearables_5,Electronics,Wearables,Atlas,638.84,882.98

In [325]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30400 entries, 0 to 30399
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             30400 non-null  object
 1   order_date_raw       30400 non-null  object
 2   customer_id          29872 non-null  object
 3   product_id           30307 non-null  object
 4   region_raw           30400 non-null  object
 5   sales_channel_raw    30400 non-null  object
 6   payment_method_raw   30400 non-null  object
 7   quantity_raw         30270 non-null  float64
 8   unit_price_raw       30300 non-null  object
 9   discount_pct_raw     30323 non-null  float64
 10  status_raw           30400 non-null  object
 11  shipping_days_raw    30320 non-null  float64
 12  customer_rating_raw  15243 non-null  float64
dtypes: float64(4), object(9)
memory usage: 3.0+ MB

In [326]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           5000 non-null   object
 1   signup_date           5000 non-null   object
 2   customer_segment_raw  5000 non-null   object
 3   loyalty_tier          5000 non-null   object
 4   age_group             5000 non-null   object
 5   home_region_raw       5000 non-null   object
dtypes: object(6)
memory usage: 234.5+ KB

In [327]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    120 non-null    object
 1   product_name  120 non-null    object
 2   category      120 non-null    object
 3   subcategory   120 non-null    object
 4   brand         120 non-null    object
 5   cost_price    120 non-null    float64
 6   list_price    120 non-null    float64
dtypes: float64(2), object(5)
memory usage: 6.7+ KB

In [328]:
orders["order_id"].duplicated().sum()

np.int64(400)

In [329]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [330]:
products["product_id"].duplicated().sum()

np.int64(0)

In [331]:
orders = orders.drop_duplicates().copy()

In [332]:
orders.duplicated().sum()

np.int64(0)

In [333]:
orders["status_raw"].value_counts()

status_raw
DELIVERED      17640
CANCELLED       4908
PENDING         4014
RETURNED        2649
delivered        183
Delivered        179
 DELIVERED       144
cancelled         49
 CANCELLED        48
 PENDING          44
Pending           36
Cancelled         33
pending           26
returned          20
 RETURNED         17
Returned          10
Name: count, dtype: int64

In [334]:
orders["region_clean"] = orders["region_raw"].str.strip().str.upper()
orders["region_clean"].value_counts()

region_clean
MARRAKECH     4390
KENITRA       4294
AGADIR        4293
CASABLANCA    4282
FES           4275
RABAT         4252
TANGER        4214
Name: count, dtype: int64

In [335]:
orders["sales_channel_clean"] =orders["sales_channel_raw"].str.strip().str.upper()
orders["sales_channel_clean"].value_counts()

sales_channel_clean
MOBILE APP     9039
MARKETPLACE    7533
WEBSITE        7492
STORE          5936
Name: count, dtype: int64

In [336]:
orders["payment_method_clean"] =orders["payment_method_raw"].str.strip().str.upper()
orders["payment_method_clean"].value_counts()

payment_method_clean
CARD             7532
WALLET           7530
BANK TRANSFER    7471
CASH             7467
Name: count, dtype: int64

In [337]:
orders["status_clean"] = orders["status_raw"].str.strip().str.upper()
orders["status_clean"].value_counts()

status_clean
DELIVERED    18146
CANCELLED     5038
PENDING       4120
RETURNED      2696
Name: count, dtype: int64

In [338]:
orders["order_date_raw"].head(15)

0     2025-07-20
1     2025-11-18
2     2025-11-13
3     2025-04-24
4     05-01-2025
5     2025-10-12
6     2025-10-18
7     19/08/2025
8     2025-05-02
9     2025-10-07
10    2025-12-24
11    11-18-2025
12    2025-05-28
13    2025-11-27
14    2025-11-06
Name: order_date_raw, dtype: object

In [339]:
orders["order_date_raw"].str.replace(r"\d", "D", regex=True).value_counts()

order_date_raw
DDDD-DD-DD    25154
DD-DD-DDDD     2431
DD/DD/DDDD     2415
Name: count, dtype: int64

In [340]:
orders[
    orders["order_date_raw"].str.contains("/")
]["order_date_raw"].head(10)

7      19/08/2025
34     30/07/2025
36     18/12/2025
66     02/10/2025
68     21/10/2025
75     30/12/2025
81     25/10/2025
83     11/10/2025
120    05/06/2025
122    09/08/2025
Name: order_date_raw, dtype: object

In [341]:
orders[
    orders["order_date_raw"].str.match(r"^\d{2}-\d{2}-\d{4}$")
]["order_date_raw"].head(10)

4      05-01-2025
11     11-18-2025
24     04-23-2025
74     05-28-2025
85     04-28-2025
142    12-28-2025
145    04-18-2025
153    10-15-2025
156    06-28-2025
157    01-23-2025
Name: order_date_raw, dtype: object

In [342]:
mask_ymd= orders["order_date_raw"].str.match(r"^\d{4}-\d{2}-\d{2}$")

mask_dmy= orders["order_date_raw"].str.match(r"^\d{2}/\d{2}/\d{4}$")

mask_mdy=orders["order_date_raw"].str.match(r"^\d{2}-\d{2}-\d{4}$")

In [343]:
mask_ymd.sum()

np.int64(25154)

In [344]:
mask_dmy.sum()

np.int64(2415)

In [345]:
mask_mdy.sum()

np.int64(2431)

In [346]:
orders["order_date_clean"] = pd.NaT

In [347]:
orders.loc[mask_ymd,"order_date_clean"]=pd.to_datetime(
   orders.loc[ mask_ymd,"order_date_raw"],
   format="%Y-%m-%d"
)

In [348]:
orders.loc[mask_dmy,"order_date_clean"]=pd.to_datetime(
   orders.loc[ mask_dmy,"order_date_raw"],
   format="%d/%m/%Y"
)

In [349]:
orders.loc[mask_mdy,"order_date_clean"]=pd.to_datetime(
   orders.loc[ mask_mdy,"order_date_raw"],
   format="%m-%d-%Y"
)

In [350]:
orders["order_date_clean"].isnull().sum()

np.int64(0)

In [351]:
orders["quantity_raw"].value_counts(dropna=False)

quantity_raw
 1.0    8393
 2.0    7726
 3.0    5374
 4.0    3593
 5.0    2924
 6.0    1730
 NaN     126
-1.0      71
 0.0      63
Name: count, dtype: int64

In [352]:
orders["quantity_clean"]= orders["quantity_raw"]

In [353]:
import numpy as np
orders.loc[orders["quantity_clean"]<=0, "quantity_clean"]= np.nan

In [354]:
orders["unit_price_raw"].value_counts(dropna=False)

unit_price_raw
NaN        100
-25         81
unknown     79
1342.6       4
2316.69      4
          ...
360.42       1
158.38       1
1764.9       1
805.88       1
1490.63      1
Name: count, Length: 28094, dtype: int64

In [355]:
orders["unit_price_clean"]=pd.to_numeric(
    orders["unit_price_raw"],
    errors="coerce"
)

In [356]:
orders.loc[orders["unit_price_clean"]<=0,"unit_price_clean"] = np.nan

In [357]:
orders["unit_price_clean"].value_counts(dropna=False)

unit_price_clean
NaN        260
1342.60      4
2316.69      4
76.47        3
1870.11      3
          ...
1794.25      1
774.18       1
360.42       1
158.38       1
550.61       1
Name: count, Length: 28092, dtype: int64

In [358]:
orders["discount_pct_raw"].value_counts(dropna=False)

discount_pct_raw
 10.0     6284
 0.0      5595
 15.0     5081
 5.0      5023
 20.0     3763
 25.0     2306
 30.0     1738
 NaN        75
 105.0      72
-10.0       63
Name: count, dtype: int64

In [359]:
orders["discount_pct_clean"] = orders["discount_pct_raw"]

In [360]:
orders.loc[(orders["discount_pct_clean"] < 0) | (orders["discount_pct_clean"] > 100) , "discount_pct_clean"]= np.nan

In [361]:
orders["discount_pct_clean"].value_counts(dropna=False)

discount_pct_clean
10.0    6284
0.0     5595
15.0    5081
5.0     5023
20.0    3763
25.0    2306
30.0    1738
NaN      210
Name: count, dtype: int64

In [362]:
orders["shipping_days_raw"].value_counts(dropna=False)

shipping_days_raw
 5.0     6381
 4.0     6313
 6.0     4774
 3.0     4576
 7.0     2646
 2.0     2470
 8.0     1159
 1.0     1078
 9.0      353
 10.0      78
 NaN       77
 0.0       42
-2.0       31
 11.0      19
 12.0       3
Name: count, dtype: int64

In [363]:
orders["shipping_days_clean"] = orders["shipping_days_raw"]

orders.loc[
    orders["shipping_days_clean"] < 0,
    "shipping_days_clean"
] = np.nan

In [364]:
orders["customer_rating_raw"].value_counts(dropna=False)

customer_rating_raw
NaN    14964
5.0     1930
4.3      792
4.0      782
4.2      753
4.1      745
4.4      730
3.9      678
3.8      660
4.5      658
4.6      631
3.7      630
4.7      585
3.6      553
4.8      511
3.4      491
3.5      488
4.9      440
3.3      434
3.2      353
3.1      321
3.0      270
2.9      215
2.7      196
2.8      191
2.6      152
2.4      143
2.5      140
2.3      104
2.2       92
2.1       83
2.0       69
1.9       50
1.8       36
1.5       28
1.7       26
1.6       23
1.4       18
1.0       12
1.2       10
1.1        7
1.3        6
Name: count, dtype: int64

In [365]:
orders["rating_missing"] = orders["customer_rating_raw"].isnull()

In [366]:
orders.groupby("status_clean")["rating_missing"].sum()

status_clean
CANCELLED    5038
DELIVERED    5051
PENDING      4120
RETURNED      755
Name: rating_missing, dtype: int64

In [367]:
orders["customer_rating_clean"] = orders["customer_rating_raw"]

In [368]:
orders["customer_id"].isnull().sum()

np.int64(520)

In [369]:
invalid_customer_ids = (
    orders["customer_id"].notna()
    & ~orders["customer_id"].isin(customers["customer_id"])
).sum()

invalid_customer_ids

np.int64(0)

In [370]:
invalid_product_ids = (
    orders["product_id"].notna()
    & ~orders["product_id"].isin(products["product_id"])
).sum()

invalid_product_ids

np.int64(0)

In [371]:
orders["customer_id_clean"] = orders["customer_id"].fillna("UNKNOWN")

In [372]:
orders["product_id_clean"] = orders["product_id"]

In [373]:
orders["missing_product_id"] = orders["product_id_clean"].isnull()

In [374]:
orders["missing_customer_id"] = orders["customer_id"].isnull()

In [375]:
orders["missing_customer_id"].sum()

np.int64(520)

In [376]:
orders["missing_product_id"].sum()

np.int64(90)

In [377]:
orders["validation_status"] = "VALID"

In [378]:
orders["validation_status"].value_counts()

validation_status
VALID    30000
Name: count, dtype: int64

In [379]:
orders.loc[(orders["quantity_clean"].isnull()) |(orders["unit_price_clean"].isnull()) | (orders["discount_pct_clean"].isnull()), "validation_status" ]= "REJECT"

In [380]:
orders["validation_status"].value_counts()

validation_status
VALID     29276
REJECT      724
Name: count, dtype: int64

In [381]:
valid_orders = orders[
    orders["validation_status"] == "VALID"
].copy()

rejected_orders = orders[
    orders["validation_status"] == "REJECT"
].copy()

In [382]:
valid_orders["region_clean"].value_counts()

region_clean
MARRAKECH     4277
AGADIR        4191
CASABLANCA    4182
KENITRA       4180
FES           4173
RABAT         4161
TANGER        4112
Name: count, dtype: int64

In [383]:
rejected_orders.shape

(724, 29)

In [384]:
customers["customer_segment_raw"].value_counts(dropna=False)

customer_segment_raw
REGULAR      2783
NEW          1390
VIP           729
 REGULAR       24
Regular        20
regular        18
New            10
new             6
 VIP            6
 NEW            5
Vip             5
vip             4
Name: count, dtype: int64

In [385]:
customers["customer_segment_clean"] = customers["customer_segment_raw"].str.strip().str.upper()

In [386]:
customers["customer_segment_clean"].value_counts(dropna=False)

customer_segment_clean
REGULAR    2845
NEW        1411
VIP         744
Name: count, dtype: int64

In [387]:
customers["home_region_clean"] = customers["home_region_raw"].str.strip().str.upper()

In [388]:
customers["home_region_clean"].value_counts(dropna=False)

home_region_clean
FES           756
AGADIR        748
MARRAKECH     724
TANGER        697
RABAT         695
CASABLANCA    693
KENITRA       687
Name: count, dtype: int64

In [389]:
customers["loyalty_tier"].value_counts(dropna=False)

loyalty_tier
BRONZE    2796
SILVER    1841
GOLD       363
Name: count, dtype: int64

In [390]:
customers["age_group"].value_counts(dropna=False)

age_group
25-34    1729
35-44    1221
18-24     818
45-54     738
55+       494
Name: count, dtype: int64

In [391]:
customers["signup_date"].head(1)

0    2025-11-24
Name: signup_date, dtype: object

In [392]:
customers["signup_date"].dtype

dtype('O')

In [393]:
customers["signup_date"].str.replace(r"\d", "D", regex=True).value_counts()

signup_date
DDDD-DD-DD    5000
Name: count, dtype: int64

In [394]:
customers["signup_date_clean"] = pd.to_datetime(
    customers["signup_date"],
    format= "%Y-%m-%d"
)

In [395]:
customers["signup_date_clean"].dtype

dtype('<M8[ns]')

In [396]:
customers["signup_date_clean"].isnull().sum()

np.int64(0)

In [397]:
products["category"].value_counts(dropna=False)

category
Electronics    20
Fashion        20
Home           20
Beauty         20
Sports         20
Accessories    20
Name: count, dtype: int64

In [398]:

products["subcategory"].value_counts(dropna=False)

subcategory
Outdoor      11
Phones        8
Kitchen       7
Men           7
Keyboards     7
Furniture     6
Women         6
Fragrance     6
Wearables     5
Cases         5
Skincare      5
Bags          5
Makeup        5
Chargers      4
Audio         4
Haircare      4
Mice          4
Running       4
Lighting      4
Laptops       3
Football      3
Decor         3
Shoes         2
Fitness       2
Name: count, dtype: int64

In [399]:

products["brand"].value_counts(dropna=False)

brand
Aura      18
Nova      18
Nexa      17
Pulse     15
Atlas     14
UrbanX    14
Zenith    12
Vertex    12
Name: count, dtype: int64

In [400]:
products[["cost_price", "list_price"]].dtypes

cost_price    float64
list_price    float64
dtype: object

In [401]:
products["cost_price"].value_counts(dropna=False)

cost_price
84.02      1
1230.99    1
92.44      1
427.98     1
638.84     1
          ..
806.61     1
1502.09    1
1042.94    1
1537.68    1
639.00     1
Name: count, Length: 120, dtype: int64

In [402]:
products["list_price"].value_counts(dropna=False)

list_price
124.67     1
2472.26    1
132.73     1
749.34     1
882.98     1
          ..
1509.47    1
1988.26    1
1896.02    1
2159.77    1
1276.90    1
Name: count, Length: 120, dtype: int64

In [403]:
products["product_name"].value_counts(dropna=False)

product_name
Nexa_Phones_1           1
Atlas_Phones_2          1
Nova_Phones_3           1
Nova_Wearables_4        1
Pulse_Wearables_5       1
                       ..
Zenith_Mice_116         1
Vertex_Cases_117        1
Pulse_Mice_118          1
Nexa_Mice_119           1
Zenith_Keyboards_120    1
Name: count, Length: 120, dtype: int64

In [404]:
valid_orders = valid_orders.merge(
    customers[
        [
            "customer_id",
            "signup_date_clean",
            "customer_segment_clean",
            "loyalty_tier",
            "age_group",
            "home_region_clean"
        ]
    ],
    on="customer_id",
    how="left",
    validate="many_to_one",
    indicator="customer_merge_status"
)

In [405]:
valid_orders["customer_merge_status"].value_counts(dropna=False)

customer_merge_status
both          28767
left_only       509
right_only        0
Name: count, dtype: int64

In [406]:
valid_orders = valid_orders.merge(
    products[
        [
            "product_id",
            "product_name",
            "category",
            "subcategory",
            "brand",
            "cost_price",
            "list_price"
        ]
    ],
    on="product_id",
    how="left",
    validate="many_to_one",
    indicator="product_merge_status"
)

In [407]:
valid_orders["product_merge_status"].value_counts(dropna= False)

product_merge_status
both          29190
left_only        86
right_only        0
Name: count, dtype: int64

In [408]:
valid_orders["gross_amount"]= (valid_orders["quantity_clean"] * valid_orders["unit_price_clean"])

In [409]:
valid_orders[["unit_price_clean","quantity_clean","gross_amount"]].head()

   unit_price_clean  quantity_clean  gross_amount
0           3322.70             1.0       3322.70
1            409.62             5.0       2048.10
2           2262.94             4.0       9051.76
3           1916.70             1.0       1916.70
4           2125.78             1.0       2125.78

In [410]:
valid_orders["discount_amount"] = (valid_orders["gross_amount"] * valid_orders["discount_pct_clean"]) / 100

In [411]:
valid_orders[["unit_price_clean","quantity_clean","gross_amount","discount_amount"]].head()

   unit_price_clean  quantity_clean  gross_amount  discount_amount
0           3322.70             1.0       3322.70          664.540
1            409.62             5.0       2048.10          409.620
2           2262.94             4.0       9051.76            0.000
3           1916.70             1.0       1916.70            0.000
4           2125.78             1.0       2125.78          318.867

In [412]:
valid_orders["net_amount"] = (valid_orders["gross_amount"] - valid_orders["discount_amount"])

In [413]:
valid_orders[["unit_price_clean","quantity_clean","gross_amount","discount_amount","net_amount"]].head()

   unit_price_clean  quantity_clean  gross_amount  discount_amount  net_amount
0           3322.70             1.0       3322.70          664.540    2658.160
1            409.62             5.0       2048.10          409.620    1638.480
2           2262.94             4.0       9051.76            0.000    9051.760
3           1916.70             1.0       1916.70            0.000    1916.700
4           2125.78             1.0       2125.78          318.867    1806.913

In [414]:
valid_orders["realized_revenue"] = 0

In [415]:
valid_orders.loc[valid_orders["status_clean"] == "DELIVERED" , "realized_revenue"] = valid_orders["net_amount"]

C:\Users\slamj\AppData\Local\Temp\ipykernel_31796\3268507258.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[2658.16  9051.76  2146.752 ...  268.328 6933.132 1380.65 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  valid_orders.loc[valid_orders["status_clean"] == "DELIVERED" , "realized_revenue"] = valid_orders["net_amount"]

In [416]:
valid_orders[[
    "status_clean",
    "net_amount",
    "realized_revenue"
]].head(10)

  status_clean  net_amount  realized_revenue
0    DELIVERED   2658.1600         2658.1600
1    CANCELLED   1638.4800            0.0000
2    DELIVERED   9051.7600         9051.7600
3    CANCELLED   1916.7000            0.0000
4      PENDING   1806.9130            0.0000
5    DELIVERED   2146.7520         2146.7520
6    DELIVERED   3486.6660         3486.6660
7    DELIVERED    468.0185          468.0185
8      PENDING   2227.2500            0.0000
9    DELIVERED   3108.7990         3108.7990

In [417]:
valid_orders["cost_amount"] = (valid_orders["cost_price"] * valid_orders["quantity_clean"])

In [418]:
valid_orders["cost_amount"].value_counts(dropna=False)

cost_amount
1538.36    92
622.35     87
NaN        86
1611.73    85
3167.18    85
           ..
1714.50     7
3339.36     6
8221.08     6
9670.38     6
1946.28     5
Name: count, Length: 720, dtype: int64

In [419]:
valid_orders[["quantity_clean", "cost_price", "cost_amount"]].head()

   quantity_clean  cost_price  cost_amount
0             1.0     1781.56      1781.56
1             5.0      329.76      1648.80
2             4.0     1348.83      5395.32
3             1.0     1538.36      1538.36
4             1.0     1551.12      1551.12

In [420]:
valid_orders["realized_cost"] = 0.0

In [421]:
valid_orders.loc[valid_orders["status_clean"] == "DELIVERED", "realized_cost" ] = valid_orders["cost_amount"]

In [422]:
valid_orders[[
    "status_clean",
    "cost_amount",
    "realized_cost"
]].head(10)

  status_clean  cost_amount  realized_cost
0    DELIVERED      1781.56        1781.56
1    CANCELLED      1648.80           0.00
2    DELIVERED      5395.32        5395.32
3    CANCELLED      1538.36           0.00
4      PENDING      1551.12           0.00
5    DELIVERED      2008.74        2008.74
6    DELIVERED      1927.88        1927.88
7    DELIVERED       324.38         324.38
8      PENDING      1324.33           0.00
9    DELIVERED      1708.46        1708.46

In [423]:
valid_orders["profit_amount"] = (valid_orders["realized_revenue"] - valid_orders["realized_cost"])

In [424]:
valid_orders[[
    "status_clean",
    "cost_amount",
    "realized_cost",
    "realized_revenue",
    "profit_amount"
]].head(10)

  status_clean  cost_amount  realized_cost  realized_revenue  profit_amount
0    DELIVERED      1781.56        1781.56         2658.1600       876.6000
1    CANCELLED      1648.80           0.00            0.0000         0.0000
2    DELIVERED      5395.32        5395.32         9051.7600      3656.4400
3    CANCELLED      1538.36           0.00            0.0000         0.0000
4      PENDING      1551.12           0.00            0.0000         0.0000
5    DELIVERED      2008.74        2008.74         2146.7520       138.0120
6    DELIVERED      1927.88        1927.88         3486.6660      1558.7860
7    DELIVERED       324.38         324.38          468.0185       143.6385
8      PENDING      1324.33           0.00            0.0000         0.0000
9    DELIVERED      1708.46        1708.46         3108.7990      1400.3390

In [425]:
total_realized_revenue = valid_orders["realized_revenue"].sum()

In [426]:
total_realized_revenue

np.float64(63643547.519)

In [427]:
total_profit = valid_orders["profit_amount"].sum()

In [428]:
total_profit

np.float64(20179584.95)

In [429]:
valid_orders["status_clean"].value_counts()

status_clean
DELIVERED    17696
CANCELLED     4927
PENDING       4026
RETURNED      2627
Name: count, dtype: int64

In [430]:
averege_order_value = total_realized_revenue / 17696

In [431]:
averege_order_value

np.float64(3596.493417665009)

In [432]:
total_valid_orders = len(valid_orders)

In [433]:
total_valid_orders

29276

In [434]:
delivered_orders= (valid_orders["status_clean"]== "DELIVERED").sum()

In [435]:
delivery_rate = delivered_orders / total_valid_orders * 100

In [436]:
delivery_rate

np.float64(60.44541604044268)

In [437]:
cancelled_orders = (valid_orders["status_clean"] == "CANCELLED").sum()

In [438]:
cancel_rate = cancelled_orders / total_valid_orders * 100

In [439]:
cancel_rate

np.float64(16.82948490230906)

In [440]:
returned_orders = (valid_orders["status_clean"] == "RETURNED").sum()

In [441]:
return_rate = returned_orders / total_valid_orders * 100

In [442]:
return_rate

np.float64(8.97322038529854)

In [443]:
pending_orders = (valid_orders["status_clean"] == "PENDING").sum()

In [444]:
pending_rate = pending_orders / total_valid_orders * 100

In [445]:
pending_rate

np.float64(13.751878671949719)

In [446]:
profit_margin =(total_profit / total_realized_revenue) * 100

In [447]:
profit_margin

np.float64(31.707196937718834)

In [448]:
known_profit_orders = valid_orders[
    valid_orders["profit_amount"].notna()
]

In [449]:
known_profit = known_profit_orders["profit_amount"].sum()

In [450]:
known_revenue = known_profit_orders["realized_revenue"].sum()

In [451]:
accurate_profit_margin = (
    known_profit / known_revenue
) * 100

In [452]:
accurate_profit_margin

np.float64(31.8126248725498)

In [453]:
valid_orders["month"] = valid_orders["order_date_clean"].dt.to_period("M")

In [454]:
valid_orders[["month","order_date_clean" ]].head()

     month order_date_clean
0  2025-07       2025-07-20
1  2025-11       2025-11-18
2  2025-11       2025-11-13
3  2025-04       2025-04-24
4  2025-05       2025-05-01

In [455]:
monthly_kpi  = valid_orders.groupby("month").agg(
    total_orders= ("order_id","count"),
    total_revenue=("realized_revenue","sum"),
    total_profit= ("profit_amount","sum")
)

In [456]:
monthly_kpi

         total_orders  total_revenue  total_profit
month
2025-01          2474   5.458223e+06  1.763081e+06
2025-02          2134   4.658294e+06  1.442755e+06
2025-03          2530   5.452929e+06  1.749432e+06
2025-04          2337   5.063464e+06  1.607882e+06
2025-05          2508   5.283720e+06  1.688084e+06
2025-06          2416   5.178267e+06  1.660645e+06
2025-07          2525   5.321399e+06  1.697004e+06
2025-08          2534   5.643780e+06  1.845737e+06
2025-09          2364   5.028394e+06  1.603936e+06
2025-10          2430   5.496072e+06  1.784599e+06
2025-11          2318   4.792230e+06  1.375231e+06
2025-12          2706   6.266776e+06  1.961199e+06

In [457]:
monthly_kpi["revenue_growth_pct"] = monthly_kpi["total_revenue"].pct_change() * 100

In [458]:
monthly_kpi["orders_growth_pct"] = monthly_kpi["total_orders"].pct_change() * 100

In [459]:
monthly_kpi

,total_orders,total_revenue,total_profit,revenue_growth_pct,orders_growth_pct
month,,,,,
2025-01,2474,5.458223e+06,1.763081e+06,NaN,NaN
2025-02,2134,4.658294e+06,1.442755e+06,-14.655485,-13.742926
2025-03,2530,5.452929e+06,1.749432e+06,17.058498,18.556701
2025-04,2337,5.063464e+06,1.607882e+06,-7.142305,-7.628458
2025-05,2508,5.283720e+06,1.688084e+06,4.349906,7.317073
2025-06,2416,5.178267e+06,1.660645e+06,-1.995805,-3.668262
2025-07,2525,5.321399e+06,1.697004e+06,2.764094,4.511589
2025-08,2534,5.643780e+06,1.845737e+06,6.058197,0.356436
2025-09,2364,5.028394e+06,1.603936e+06,-10.903796,-6.708761
2025-10,2430,5.496072e+06,1.784599e+06,9.300738,2.791878
2025-11,2318,4.792230e+06,1.375231e+06,-12.806261,-4.609053
2025-12,2706,6.266776e+06,1.961199e+06,30.769504,16.738568

In [460]:
monthly_status = valid_orders.groupby(
 ["month", "status_clean"]).size().unstack()

In [461]:
monthly_status

status_clean  CANCELLED  DELIVERED  PENDING  RETURNED
month
2025-01             426       1469      355       224
2025-02             362       1293      284       195
2025-03             449       1512      349       220
2025-04             360       1434      339       204
2025-05             451       1479      342       236
2025-06             408       1467      326       215
2025-07             438       1531      357       199
2025-08             416       1539      346       233
2025-09             453       1337      377       197
2025-10             405       1477      328       220
2025-11             378       1419      304       217
2025-12             381       1739      319       267

In [462]:
monthly_kpi["delivered_orders"] = monthly_status["DELIVERED"]

In [463]:
monthly_kpi["AOV"] = (
    monthly_kpi["total_revenue"] /
    monthly_kpi["delivered_orders"]
)

In [464]:
monthly_kpi.loc[
    ["2025-01", "2025-02"],
    ["total_revenue", "delivered_orders", "AOV"]
]

         total_revenue  delivered_orders          AOV
month
2025-01   5.458223e+06              1469  3715.604392
2025-02   4.658294e+06              1293  3602.702114

In [465]:
category_kpi = valid_orders.groupby("category").agg(
    total_orders= ("order_id","count"),
    total_revenue= ("realized_revenue","sum"),
    total_profit=("profit_amount","sum")
)
category_kpi

             total_orders  total_revenue  total_profit
category
Accessories          4821   1.195480e+07  3.852952e+06
Beauty               4848   1.090254e+07  3.220185e+06
Electronics          4913   9.330118e+06  3.145773e+06
Fashion              4728   1.026675e+07  3.341444e+06
Home                 4968   9.518674e+06  2.812181e+06
Sports               4912   1.145976e+07  3.807050e+06

In [466]:
category_delivered = valid_orders[
    valid_orders["status_clean"] == "DELIVERED"
].groupby("category")["order_id"].count()

In [467]:
category_delivered

category
Accessories    2929
Beauty         2974
Electronics    2930
Fashion        2728
Home           3067
Sports         3016
Name: order_id, dtype: int64

In [468]:
category_kpi["delivered_orders"] = category_delivered

In [469]:
category_kpi["AOV"] = (
    category_kpi["total_revenue"] /
    category_kpi["delivered_orders"]
)

In [470]:
category_kpi

,total_orders,total_revenue,total_profit,delivered_orders,AOV
category,,,,,
Accessories,4821,1.195480e+07,3.852952e+06,2929,4081.528442
Beauty,4848,1.090254e+07,3.220185e+06,2974,3665.950601
Electronics,4913,9.330118e+06,3.145773e+06,2930,3184.340588
Fashion,4728,1.026675e+07,3.341444e+06,2728,3763.471267
Home,4968,9.518674e+06,2.812181e+06,3067,3103.578223
Sports,4912,1.145976e+07,3.807050e+06,3016,3799.653571

In [471]:
known_profit_orders = valid_orders[
    valid_orders["profit_amount"].notna()
]

In [472]:
category_profit = known_profit_orders.groupby("category").agg(
    known_revenue = ("realized_revenue","sum"),
    known_profit  = ("profit_amount","sum")
)

In [473]:
category_profit["profit_margin"] = (category_profit["known_profit"] / category_profit["known_revenue"] * 100)

In [474]:
category_profit

             known_revenue  known_profit  profit_margin
category
Accessories   1.195480e+07  3.852952e+06      32.229339
Beauty        1.090254e+07  3.220185e+06      29.536111
Electronics   9.330118e+06  3.145773e+06      33.716321
Fashion       1.026675e+07  3.341444e+06      32.546274
Home          9.518674e+06  2.812181e+06      29.543828
Sports        1.145976e+07  3.807050e+06      33.221038

In [475]:
segment_kpi = valid_orders.groupby("customer_segment_clean").agg(
    total_orders = ("order_id","count"),
    total_revenue = ("realized_revenue","sum"),
    total_profit = ("profit_amount","sum") 
)
segment_kpi

                        total_orders  total_revenue  total_profit
customer_segment_clean
NEW                             8120   1.781763e+07  5.652946e+06
REGULAR                        16245   3.484481e+07  1.104795e+07
VIP                             4402   9.963784e+06  3.154510e+06

In [476]:
segment_kpi["delivered_orders"] = valid_orders[
    valid_orders["status_clean"] == "DELIVERED"
].groupby("customer_segment_clean")["order_id"].count()

In [477]:
segment_kpi["AOV"] = (segment_kpi["total_revenue"] / segment_kpi["delivered_orders"])

In [478]:
segment_kpi

,total_orders,total_revenue,total_profit,delivered_orders,AOV
customer_segment_clean,,,,,
NEW,8120,1.781763e+07,5.652946e+06,4927,3616.323533
REGULAR,16245,3.484481e+07,1.104795e+07,9770,3566.510352
VIP,4402,9.963784e+06,3.154510e+06,2718,3665.851521

In [479]:
segment_profit = known_profit_orders.groupby("customer_segment_clean").agg(
    known_revenue = ("realized_revenue","sum"),
    known_profit  = ("profit_amount","sum")
)

In [480]:
segment_profit["profit_margin"] = (segment_profit["known_profit"] / segment_profit["known_revenue"] * 100)
segment_profit

                        known_revenue  known_profit  profit_margin
customer_segment_clean
NEW                      1.774086e+07  5.652946e+06      31.863988
REGULAR                  3.474054e+07  1.104795e+07      31.801316
VIP                      9.933896e+06  3.154510e+06      31.755014

In [481]:
loyalty_tier_kpi = valid_orders.groupby("loyalty_tier").agg(
    total_orders = ("order_id","count"),
    total_revenue = ("realized_revenue","sum"),
    total_profit = ("profit_amount","sum")
)
loyalty_tier_kpi

              total_orders  total_revenue  total_profit
loyalty_tier
BRONZE               15968   3.457981e+07  1.093513e+07
GOLD                  2125   4.778418e+06  1.497504e+06
SILVER               10674   2.326799e+07  7.422770e+06

In [482]:
loyalty_tier_kpi["delivered_orders"] = valid_orders[
    valid_orders["status_clean"] == "DELIVERED"
].groupby("loyalty_tier")["order_id"].count()

In [483]:
loyalty_tier_kpi["AOV"] = loyalty_tier_kpi["total_revenue"] / loyalty_tier_kpi["delivered_orders"]

In [484]:
loyalty_tier_kpi

,total_orders,total_revenue,total_profit,delivered_orders,AOV
loyalty_tier,,,,,
BRONZE,15968,3.457981e+07,1.093513e+07,9636,3588.606483
GOLD,2125,4.778418e+06,1.497504e+06,1325,3606.353317
SILVER,10674,2.326799e+07,7.422770e+06,6454,3605.203967

In [485]:
loyalty_profit = known_profit_orders.groupby("loyalty_tier").agg(
    known_revenue = ("realized_revenue","sum"),
    known_profit = ("profit_amount","sum")
)
loyalty_profit

              known_revenue  known_profit
loyalty_tier
BRONZE         3.446608e+07  1.093513e+07
GOLD           4.763501e+06  1.497504e+06
SILVER         2.318572e+07  7.422770e+06

In [486]:
loyalty_profit["profit_margin"] = (loyalty_profit["known_profit"] / loyalty_profit["known_revenue"] )* 100
loyalty_profit

              known_revenue  known_profit  profit_margin
loyalty_tier
BRONZE         3.446608e+07  1.093513e+07      31.727232
GOLD           4.763501e+06  1.497504e+06      31.437053
SILVER         2.318572e+07  7.422770e+06      32.014398

In [487]:
age_group_kpi = valid_orders.groupby("age_group").agg(
    total_orders = ("order_id","count"),
    total_revenue = ("realized_revenue","sum"),
    total_profit= ("profit_amount","sum")
)
age_group_kpi

           total_orders  total_revenue  total_profit
age_group
18-24              4566   1.035788e+07  3.302281e+06
25-34             10019   2.153723e+07  6.800798e+06
35-44              7103   1.530704e+07  4.858225e+06
45-54              4305   9.485494e+06  3.006828e+06
55+                2774   5.938571e+06  1.887274e+06

In [488]:
age_group_kpi["delivered_orders"] = valid_orders[
    valid_orders["status_clean"]== "DELIVERED"
].groupby("age_group")["order_id"].count()

In [489]:
age_group_kpi["AOV"] = age_group_kpi["total_revenue"] / age_group_kpi ["delivered_orders"]

In [490]:
age_group_kpi

,total_orders,total_revenue,total_profit,delivered_orders,AOV
age_group,,,,,
18-24,4566,1.035788e+07,3.302281e+06,2850,3634.343167
25-34,10019,2.153723e+07,6.800798e+06,6027,3573.458049
35-44,7103,1.530704e+07,4.858225e+06,4223,3624.684228
45-54,4305,9.485494e+06,3.006828e+06,2634,3601.174782
55+,2774,5.938571e+06,1.887274e+06,1681,3532.760895

In [491]:
age_profit = known_profit_orders.groupby("age_group").agg(
    known_revenue= ("realized_revenue","sum"),
    known_profit= ("profit_amount","sum")
)

In [492]:
age_profit["margin_profit"] = age_profit["known_profit"] / age_profit["known_revenue"] * 100

In [493]:
age_profit

           known_revenue  known_profit  margin_profit
age_group
18-24       1.031189e+07  3.302281e+06      32.024023
25-34       2.147579e+07  6.800798e+06      31.667279
35-44       1.525964e+07  4.858225e+06      31.837083
45-54       9.452972e+06  3.006828e+06      31.808282
55+         5.915010e+06  1.887274e+06      31.906521

In [494]:
def build_kpi(group_col):

    kpi = valid_orders.groupby(group_col).agg(
        total_orders=("order_id", "count"),
        total_revenue=("realized_revenue", "sum"),
        total_profit=("profit_amount", "sum")
    )

    delivered = valid_orders[
        valid_orders["status_clean"] == "DELIVERED"
    ].groupby(group_col)["order_id"].count()

    kpi["delivered_orders"] = delivered

    kpi["AOV"] = (
        kpi["total_revenue"] /
        kpi["delivered_orders"]
    )

    known = known_profit_orders.groupby(group_col).agg(
        known_revenue=("realized_revenue", "sum"),
        known_profit=("profit_amount", "sum")
    )

    kpi["profit_margin"] = (
        known["known_profit"] /
        known["known_revenue"]
    ) * 100

    return kpi

In [495]:
region_kpi = build_kpi("region_clean")

channel_kpi = build_kpi("sales_channel_clean")

payment_kpi = build_kpi("payment_method_clean")

In [496]:
region_kpi.sort_values("total_revenue", ascending=False)

,total_orders,total_revenue,total_profit,delivered_orders,AOV,profit_margin
region_clean,,,,,,
MARRAKECH,4277,9.476476e+06,3.022627e+06,2608,3633.618037,32.061264
KENITRA,4180,9.307581e+06,2.982539e+06,2534,3673.078358,32.124761
TANGER,4112,9.123205e+06,2.907680e+06,2513,3630.404023,31.985593
RABAT,4161,9.109117e+06,2.848307e+06,2529,3601.865065,31.328855
FES,4173,9.077618e+06,2.870472e+06,2513,3612.263369,31.756352
CASABLANCA,4182,8.899554e+06,2.850414e+06,2499,3561.246140,32.093750
AGADIR,4191,8.649997e+06,2.697546e+06,2500,3459.998843,31.301561

In [497]:
channel_kpi.sort_values("total_revenue", ascending=False)

,total_orders,total_revenue,total_profit,delivered_orders,AOV,profit_margin
sales_channel_clean,,,,,,
MOBILE APP,8807,1.912172e+07,6.065901e+06,5367,3562.831992,31.830681
MARKETPLACE,7355,1.610133e+07,5.027603e+06,4446,3621.531177,31.364936
WEBSITE,7319,1.572259e+07,5.040190e+06,4399,3574.128869,32.129673
STORE,5795,1.269791e+07,4.045892e+06,3484,3644.634819,31.959434

In [498]:
payment_kpi.sort_values("total_revenue", ascending=False)

,total_orders,total_revenue,total_profit,delivered_orders,AOV,profit_margin
payment_method_clean,,,,,,
WALLET,7335,1.616401e+07,5.087796e+06,4458,3625.843689,31.613902
BANK TRANSFER,7290,1.616330e+07,5.114746e+06,4469,3616.759214,31.762737
CARD,7363,1.578635e+07,5.000912e+06,4423,3569.148934,31.759063
CASH,7288,1.552989e+07,4.976131e+06,4346,3573.376367,32.125407

In [499]:
shipping_by_status = valid_orders.groupby("status_clean").agg(
    avg_shipping_days=("shipping_days_clean", "mean"),
    total_orders=("order_id", "count")
)

shipping_by_status

              avg_shipping_days  total_orders
status_clean
CANCELLED              4.577252          4927
DELIVERED              4.495437         17696
PENDING                4.503488          4026
RETURNED               5.517809          2627

In [500]:
rating_by_status = valid_orders.groupby("status_clean").agg(
    avg_rating=("customer_rating_clean", "mean"),
    total_ratings=("customer_rating_clean", "count")
)

rating_by_status

              avg_rating  total_ratings
status_clean
CANCELLED            NaN              0
DELIVERED       4.166148          12782
PENDING              NaN              0
RETURNED        2.775884           1895

In [501]:
channel_operations = valid_orders.groupby("sales_channel_clean").agg(
    avg_shipping_days=("shipping_days_clean", "mean"),
    avg_rating=("customer_rating_clean", "mean"),
    total_orders=("order_id", "count")
)

channel_operations

                     avg_shipping_days  avg_rating  total_orders
sales_channel_clean
MARKETPLACE                   5.365421    3.978267          7355
MOBILE APP                    4.354978    3.986021          8807
STORE                         4.333506    3.978692          5795
WEBSITE                       4.343171    4.002281          7319

In [502]:
channel_status = valid_orders.groupby(
    ["sales_channel_clean", "status_clean"]
).size().unstack(fill_value=0)

channel_status

status_clean         CANCELLED  DELIVERED  PENDING  RETURNED
sales_channel_clean
MARKETPLACE               1272       4446      972       665
MOBILE APP                1466       5367     1187       787
STORE                      976       3484      813       522
WEBSITE                   1213       4399     1054       653

In [503]:
channel_status["total_orders"] = channel_status.sum(axis=1)

channel_status["return_rate"] = (
    channel_status["RETURNED"] /
    channel_status["total_orders"]
) * 100

channel_status

status_clean,CANCELLED,DELIVERED,PENDING,RETURNED,total_orders,return_rate
sales_channel_clean,,,,,,
MARKETPLACE,1272,4446,972,665,7355,9.041468
MOBILE APP,1466,5367,1187,787,8807,8.936074
STORE,976,3484,813,522,5795,9.007765
WEBSITE,1213,4399,1054,653,7319,8.921984

In [504]:
valid_orders.to_csv("outputs/valid_orders.csv", index=False)
rejected_orders.to_csv("outputs/rejected_orders.csv", index=False)

monthly_kpi.to_csv("outputs/monthly_kpi.csv")
category_kpi.to_csv("outputs/category_kpi.csv")
segment_kpi.to_csv("outputs/segment_kpi.csv")
loyalty_tier_kpi.to_csv("outputs/loyalty_tier_kpi.csv")
age_group_kpi.to_csv("outputs/age_group_kpi.csv")

region_kpi.to_csv("outputs/region_kpi.csv")
channel_kpi.to_csv("outputs/channel_kpi.csv")
payment_kpi.to_csv("outputs/payment_kpi.csv")

channel_status.to_csv("outputs/channel_status.csv")